org.gradle.jvmargs=-Xmx4g -XX:+UseZGC -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true

# Java toolchain
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false

# Project metadata
org.openfps.version=0.1.0-SNAPSHOT
org.openfps.java.version=21
org.openfps.project.name=OpenFPS
