/*
 * Copyright (c) 2026 Nicholas Hutter and contributors.
 * SPDX-License-Identifier: MIT
 */

package com.openfps.android.persistence;

import androidx.room.Database;
import androidx.room.RoomDatabase;

/**
 * The Room database. One table today: {@code user_profile}.
 *
 * <b>Schema version 1</b> matches the desktop SQLite schema created by
 * {@code SqliteUserProfilePort}. When either side gains a column both must
 * move together, and this version must be bumped with a migration — Room
 * refuses to open a database whose version differs from the code, which is
 * the behaviour we want rather than silently reading a stale shape.
 *
 * {@code exportSchema} is false because there is no schema-history directory
 * configured yet. Turn it on alongside the first migration, when the exported
 * JSON becomes the thing migrations are tested against.
 */
@Database(entities = {UserProfileEntity.class}, version = 1, exportSchema = false)
public abstract class OpenFpsDatabase extends RoomDatabase
{
    /** The database file name, under the app's private storage. */
    public static final String DB_NAME = "openfps-profile.db";

    /**
     * Returns the profile DAO.
     *
     * @return the DAO, generated by Room
     */
    public abstract UserProfileDao userProfileDao();
}
