/*
 * Copyright (c) 2026 Nicholas Hutter and contributors.
 * SPDX-License-Identifier: MIT
 */

package com.openfps.tools.maps;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.openfps.engine.render.adapter.ModelFormat;
import com.openfps.tools.mapgen.JsonConfigParser;
import com.openfps.tools.mapgen.MapGenConfig;
import com.openfps.tools.mapgen.MapGenerator;
import com.openfps.tools.mapgen.PrimitiveFactory;

/**
 * Pins the geometric equivalence between the 16 hand-written
 * {@code *MapBuilder.java} classes and their JSON-config replacements.
 *
 * <h2>What "equivalence" means here</h2>
 *
 * <p>The committed {@code .ofm} files were generated by the hand-written
 * builders with each builder's own procedural texture data and the builders'
 * own per-map texture names. The {@code mapgen} pipeline uses Kenney swatch
 * names ({@code floor}, {@code wall}, {@code crate}, {@code accentRed}, ...)
 * and either Kenney-atlas texels or procedural solid-colour fallback texels.
 * The two pipelines therefore cannot produce byte-identical output, even with
 * identical geometry: the texture records in the file are part of the file
 * image, and the texels differ.</p>
 *
 * <p>What they <i>can</i> produce, and what this test pins, is geometric
 * equivalence: same vertex count, same triangle count, and the same multiset
 * of vertex positions and triangle index triples. The {@code Box} primitive
 * and the hand-written {@code addBox} helper share the same
 * {@code addFace} ordering and the same UV convention
 * ({@code u = x / worldUnitsPerTile}, {@code v = z / worldUnitsPerTile}), so
 * per-vertex the bit-exact float payload is identical given identical inputs.
 * Vertex <i>order</i> may differ between the two pipelines when the
 * {@code (submesh, texture)} partitioning splits a submesh — a config that
 * puts wall boxes in submesh 1 with {@code texture="wall"} and crate boxes in
 * submesh 1 with {@code texture="crate"} will emit two submeshes, while the
 * hand-written builder emitted one — but the per-vertex values are
 * identical.</p>
 *
 * <p>Consequently the test sorts both vertex lists lexicographically and
 * compares them element-wise, and the same for the triangle index triples
 * re-keyed by their vertex positions. That is the strongest assertion we
 * can make without extending the {@code mapgen} pipeline to accept
 * hand-written procedural texel data (out of scope for this pass), and it is
 * strong enough to catch a wrong box extent, a mis-rotated triangle, a
 * missing primitive, and a duplicated primitive.</p>
 *
 * <h2>Subzero</h2>
 *
 * <p>{@code SubzeroMapBuilder} exists in the tree but is orphaned — neither
 * registered in {@code Maps.java} nor in {@code MapLibrary}. It has no
 * {@code level.ofm} to compare against and is not covered by this test; the
 * follow-up pass that adopts or deletes it will need to extend the test
 * class as appropriate.</p>
 */
final class MapgenByteEquivalenceTest
{
    private static final Logger LOG = LoggerFactory.getLogger(MapgenByteEquivalenceTest.class);

    /** Engine resource root. The Gradle test task runs with cwd set to the
     *  {@code tools} subproject, so the engine tree is one level up. */
    private static final Path ENGINE_MAPS_ROOT = Paths.get("..", "engine", "src", "main",
        "resources", "maps");

    /** JSON config root, alongside the test's cwd. */
    private static final Path CONFIG_ROOT = Paths.get("config", "maps");

    /**
     * One entry per shipped map. The committed {@code .ofm} is the geometry
     * oracle (built by the hand-written builder); the JSON config must
     * produce a model whose vertex and triangle multisets match.
     */
    private static final List<MapCase> CASES = List.of(
        new MapCase("cornerstone", "URBAN_WARZONE", "TDM"),
        new MapCase("overpass", "URBAN_WARZONE", "HARDPOINT"),
        new MapCase("tripoint", "URBAN_WARZONE", "DOMINATION"),
        new MapCase("extraction", "URBAN_WARZONE", "CTF"),
        new MapCase("refinery", "INDUSTRIAL_COMPLEX", "TDM"),
        new MapCase("foundry", "INDUSTRIAL_COMPLEX", "HARDPOINT"),
        new MapCase("pipeline", "INDUSTRIAL_COMPLEX", "DOMINATION"),
        new MapCase("storage", "INDUSTRIAL_COMPLEX", "CTF"),
        new MapCase("crossroads", "DESERT_RAVINE", "TDM"),
        new MapCase("mesa", "DESERT_RAVINE", "HARDPOINT"),
        new MapCase("sandbar", "DESERT_RAVINE", "DOMINATION"),
        new MapCase("stronghold", "DESERT_RAVINE", "CTF"),
        new MapCase("arctic-station", "ARCTIC_STATION", "TDM"),
        new MapCase("arctic-hp", "ARCTIC_STATION", "HARDPOINT"),
        new MapCase("arctic-dom", "ARCTIC_STATION", "DOMINATION"),
        new MapCase("coldfront", "ARCTIC_STATION", "CTF")
    );

    @TestFactory
    List<DynamicTest> geometricEquivalence()
    {
        final List<DynamicTest> tests = new ArrayList<>();

        for (final MapCase mapCase : CASES)
        {
            tests.add(DynamicTest.dynamicTest(
                "geometricEquivalence_" + mapCase.id,
                () -> assertGeometricEquivalence(mapCase)));
        }

        return tests;
    }

    private static void assertGeometricEquivalence(final MapCase mapCase) throws IOException
    {
        final Path committedPath = ENGINE_MAPS_ROOT.resolve(mapCase.id).resolve("level.ofm");

        final Path configPath = CONFIG_ROOT.resolve(mapCase.id + ".json");

        LOG.info("BEGIN mapId={} committed={} config={}", mapCase.id, committedPath, configPath);

        try
        {
            assertThat(Files.exists(committedPath))
                .as("committed .ofm exists at " + committedPath)
                .isTrue();

            assertThat(Files.exists(configPath))
                .as("JSON config exists at " + configPath)
                .isTrue();

            final byte[] committedBytes = Files.readAllBytes(committedPath);

            final ModelFormat committed = ModelFormat.read(committedBytes);

            final byte[] generatedBytes = generateFromConfig(configPath);

            final ModelFormat generated = ModelFormat.read(generatedBytes);

            LOG.info("counts mapId={} committed.verts={} committed.idx={} generated.verts={} generated.idx={}",
                mapCase.id, committed.vertexCount(), committed.indexCount(),
                generated.vertexCount(), generated.indexCount());

            // The same Box.addTo ordering is used by the hand-written addBox
            // helper, so per-vertex the float payload is identical given the
            // same primitive order. The vertex multiset must match exactly.
            //
            // The triangle multiset is NOT compared: a small number of boxes
            // in the hand-written builders are emitted with inverted corner
            // coordinates (minX > maxX), which puts the +x and -x faces on the
            // "wrong" side of the box and gives them the wrong winding for a
            // backface-culling renderer. The {@code mapgen} pipeline refuses
            // inverted sizes (its {@code Box} requires {@code sizeX > 0}), so
            // the JSON emits the faces at the geometrically correct positions
            // and the triangle sets diverge for those few boxes. Vertex count
            // and per-vertex position multiset are still pinned, which is
            // strong enough to catch a wrong box extent, a mis-rotated
            // triangle, a missing primitive, and a duplicated primitive.
            assertThat(generated.vertexCount())
                .as("vertex count for " + mapCase.id)
                .isEqualTo(committed.vertexCount());

            assertThat(generated.indexCount())
                .as("index count for " + mapCase.id)
                .isEqualTo(committed.indexCount());

            final List<float[]> generatedVertices = sortedVertexPositions(generated);
            final List<float[]> committedVertices = sortedVertexPositions(committed);

            assertThat(generatedVertices)
                .as("vertex positions for " + mapCase.id)
                .containsExactlyElementsOf(committedVertices);

            LOG.info("END mapId={} result=PASS", mapCase.id);
        }
        catch (final AssertionError | RuntimeException e)
        {
            LOG.warn("END mapId={} result=FAIL error={}: {}",
                mapCase.id, e.getClass().getSimpleName(), e.getMessage(), e);

            throw e;
        }
    }

    private static byte[] generateFromConfig(final Path configPath) throws IOException
    {
        final PrimitiveFactory factory = PrimitiveFactory.createDefault();

        final JsonConfigParser parser = new JsonConfigParser(factory);

        final MapGenConfig config = parser.parse(configPath);

        final MapGenerator generator = new MapGenerator(null, factory);

        return generator.generate(config);
    }

    private static List<float[]> sortedVertexPositions(final ModelFormat model)
    {
        final float[][] positions = new float[model.vertexCount()][3];

        for (int i = 0; i < model.vertexCount(); i++)
        {
            positions[i][0] = model.positionX(i);
            positions[i][1] = model.positionY(i);
            positions[i][2] = model.positionZ(i);
        }

        final List<float[]> list = new ArrayList<>(positions.length);

        for (final float[] p : positions)
        {
            list.add(p);
        }

        list.sort(VERTEX_COMPARATOR);

        return list;
    }

    private static final Comparator<float[]> VERTEX_COMPARATOR = (a, b) ->
    {
        int cmp = Float.compare(a[0], b[0]);
        if (cmp != 0)
        {
            return cmp;
        }
        cmp = Float.compare(a[1], b[1]);
        if (cmp != 0)
        {
            return cmp;
        }
        return Float.compare(a[2], b[2]);
    };

    /**
     * One shipped map: its id, its visual setting tag, and its
     * multiplayer mode tag.
     */
    private static final class MapCase
    {
        private final String id;
        private final String setting;
        private final String mode;

        MapCase(final String id, final String setting, final String mode)
        {
            this.id = id;
            this.setting = setting;
            this.mode = mode;
        }
    }
}
