/*
 * Copyright (c) 2026 Nicholas Hutter and contributors.
 * SPDX-License-Identifier: MIT
 */

package com.openfps.engine.render.adapter;

/**
 * An immutable, pre-generated mipmap pyramid for one texture.
 *
 * Render adapter — must not import from core engine packages.
 *
 * <h2>What this is and is not</h2>
 *
 * This is a <em>container</em>. It does not build a pyramid: per
 * {@code docs/ASSETS.md} section 5, mipmaps are generated by the build-time
 * asset converter and are required at runtime. A chain arrives fully formed;
 * this class validates its shape and lays it out for fast indexing. The only
 * code that constructs a chain by hand is test scaffolding.
 *
 * <h2>Texel format</h2>
 *
 * Texels are {@code RGBA8888} packed into an {@code int} — red in the most
 * significant byte, alpha in the least — which is deliberately the same
 * layout as the colour buffer. The presentation path pins the colour buffer's
 * format; the texture's format was free, so it moved to match. The result is
 * that the sampling path never swizzles a channel. Any channel shuffle
 * appearing in this class or in {@link TextureSampler} is a bug, not an
 * optimisation opportunity.
 *
 * <h2>Memory layout</h2>
 *
 * All levels live in one flat {@code int[}{@code ]}, level 0 first. A fetch is
 * therefore one array access with one bounds check, rather than the two a
 * jagged {@code int[}{@code ][}{@code ]} would cost. Because every dimension is
 * a power of two, the row stride is a shift and the wrap is an AND.
 *
 * <h2>Dimensions must be powers of two</h2>
 *
 * Enforced at construction, loudly. This is not an assumption made silently in
 * the inner loop: the constructor rejects anything else with a message naming
 * the offending value. The asset budget (512 squared, 256 squared for Kenney
 * atlases) makes the restriction free, and it buys mask-instead-of-modulo
 * wrapping on the hottest path in the engine.
 *
 * <h2>Addressing</h2>
 *
 * Out-of-range coordinates <strong>repeat</strong> (GL_REPEAT), not clamp.
 * See {@link TextureSampler} for why, and for what that means at a bilinear
 * filter footprint straddling an edge.
 *
 * Source — Lance Williams, "Pyramidal Parametrics", SIGGRAPH '83,
 * Computer Graphics 17(3), pp. 1-11. The original mipmap paper; the pyramid
 * structure and the "MIP" (multum in parvo) acronym are from it.
 */
public final class MipChain
{
    /**
     * Largest edge length accepted, well past the asset budget of 512.
     * A bound exists so a corrupt header cannot ask for a chain that would
     * overflow the flat texel index.
     */
    private static final int MAX_DIMENSION = 1 << 16;

    /** Every level's texels, concatenated, level 0 first. Never mutated after construction. */
    private final int[] texels;

    /** Index into {@link #texels} of the first texel of each level. */
    private final int[] levelOffset;

    /** Width minus one per level — the AND mask that implements repeat wrapping in x. */
    private final int[] levelWidthMask;

    /** Height minus one per level — the AND mask that implements repeat wrapping in y. */
    private final int[] levelHeightMask;

    /** log2 of each level's width — turns the row-stride multiply into a shift. */
    private final int[] levelWidthShift;

    /** Number of levels present, at least one. */
    private final int levelCount;

    /**
     * Builds a chain from pre-generated level data.
     *
     * <p>Level {@code k} must measure {@code max(1, width >> k)} by
     * {@code max(1, height >> k)} and its array length must equal that
     * product exactly. The chain may stop short of 1x1 — a partial chain is
     * legal and LOD selection clamps to whatever is here — but it may not run
     * past it.</p>
     *
     * <p>The level arrays are copied. The caller keeps ownership of what it
     * passed in and may reuse or mutate it afterwards without affecting this
     * chain.</p>
     *
     * @param width width of level 0 in texels; must be a power of two
     * @param height height of level 0 in texels; must be a power of two
     * @param levels level data, level 0 first, RGBA8888 packed, row-major
     * @throws IllegalArgumentException if any dimension is not a power of two,
     *     if there are no levels or too many, or if a level's array length
     *     does not match its expected dimensions
     */
    public MipChain(final int width, final int height, final int[][] levels)
    {
        requirePowerOfTwo(width, "width");

        requirePowerOfTwo(height, "height");

        if (levels == null || levels.length == 0)
        {
            throw new IllegalArgumentException("mip chain must have at least one level");
        }

        final int maxLevels = log2(Math.max(width, height)) + 1;

        if (levels.length > maxLevels)
        {
            throw new IllegalArgumentException(
                "mip chain for " + width + "x" + height + " has at most " + maxLevels
                    + " levels, got " + levels.length);
        }

        this.levelCount = levels.length;

        this.levelOffset = new int[levelCount];

        this.levelWidthMask = new int[levelCount];

        this.levelHeightMask = new int[levelCount];

        this.levelWidthShift = new int[levelCount];

        // MUTABLE local — running texel count across the pyramid.
        int total = 0;

        for (int level = 0; level < levelCount; level++)
        {
            final int levelWidth = Math.max(1, width >> level);

            final int levelHeight = Math.max(1, height >> level);

            final int expected = levelWidth * levelHeight;

            if (levels[level] == null || levels[level].length != expected)
            {
                throw new IllegalArgumentException(
                    "mip level " + level + " must be " + levelWidth + "x" + levelHeight
                        + " (" + expected + " texels), got " + describeLength(levels[level]));
            }

            levelOffset[level] = total;

            levelWidthMask[level] = levelWidth - 1;

            levelHeightMask[level] = levelHeight - 1;

            levelWidthShift[level] = log2(levelWidth);

            total += expected;
        }

        this.texels = new int[total];

        for (int level = 0; level < levelCount; level++)
        {
            System.arraycopy(levels[level], 0, texels, levelOffset[level], levels[level].length);
        }
    }

    /**
     * Returns the number of levels present, always at least one.
     * Level 0 is the base image; the highest valid level index is
     * {@code levelCount() - 1}.
     */
    public int levelCount()
    {
        return levelCount;
    }

    /**
     * Returns the width in texels of the given level.
     *
     * @param level level index in {@code [0, levelCount())}
     */
    public int width(final int level)
    {
        return levelWidthMask[level] + 1;
    }

    /**
     * Returns the height in texels of the given level.
     *
     * @param level level index in {@code [0, levelCount())}
     */
    public int height(final int level)
    {
        return levelHeightMask[level] + 1;
    }

    /**
     * Fetches one texel, repeating out-of-range coordinates.
     *
     * <p>This is the innermost operation in the renderer: four calls per
     * bilinear sample, one bilinear sample per pixel per overdraw. It
     * allocates nothing, branches on nothing, and compiles to two ANDs, a
     * shift, an OR and one array load. The wrap is the AND — legal only
     * because the constructor guaranteed power-of-two dimensions.</p>
     *
     * @param level level index in {@code [0, levelCount())}
     * @param x column, any value; wrapped into range
     * @param y row, any value; wrapped into range
     * @return the packed RGBA8888 texel
     */
    public int texel(final int level, final int x, final int y)
    {
        final int wrappedX = x & levelWidthMask[level];

        final int wrappedY = y & levelHeightMask[level];

        return texels[levelOffset[level] + (wrappedY << levelWidthShift[level]) + wrappedX];
    }

    // Rejects anything that is not a positive power of two, naming the value.
    private static void requirePowerOfTwo(final int value, final String name)
    {
        if (value <= 0 || value > MAX_DIMENSION || (value & (value - 1)) != 0)
        {
            throw new IllegalArgumentException(
                "texture " + name + " must be a power of two in [1, " + MAX_DIMENSION
                    + "], got " + value);
        }
    }

    // Exact base-2 logarithm of a positive power of two.
    private static int log2(final int powerOfTwo)
    {
        return Integer.numberOfTrailingZeros(powerOfTwo);
    }

    // Describes an array length for an error message, tolerating null.
    private static String describeLength(final int[] level)
    {
        if (level == null)
        {
            return "null";
        }

        return Integer.toString(level.length);
    }
}
